### ISSUE TITLE
关于排行榜日历问题

### ISSUE THREAD

**Issue by setube** [journey-ad/pixiv-viewer#60]
只有我一个人是这样吗?
https://dd-static.jd.com/ddimg/jfs/t1/113412/21/25409/1143010/629e72b5Ea24118af/36e1c931b841e932.webp
这是演示站的
https://dd-static.jd.com/ddimg/jfs/t1/88224/34/29422/468746/629e7442E5f0cdbc4/933c6dca2bc76475.webp

**Comment by SeTube** [comment]
而且不知道怎么回事,今天明明是星期2
https://dd-static.jd.com/ddimg/jfs/t1/82866/25/19633/6303/629e72f8Edfa4c8e0/f10aad369b82c8b4.jpg
而日历上却是星期5
然后演示站里的日历是能用的,日期也是正确的
