### ISSUE TITLE
pariticular 404 not found with specific pixiv id

### ISSUE THREAD

**Issue by liding58** [journey-ad/pixiv-viewer#7]
Always appreciated of your great works and help.

here is an issue when i call ***!!NSFW Link!!*** https://lab.getloli.com/pixiv-viewer/#/artwork/82660315 ***!!NSFW Link!!***
image errored out with 404 not found.

then check source and api
https://api.imjad.cn/pixiv/v2/?id=82660315
given that url:
https://pximg.pixiv-viewer.workers.dev/c/600x1200_90_webp/img-master/img/2020/06/30/22/12/58/82660315_p0_master1200.jpg

responses with identical err.

is that the api issued or cloudfrare worker proxy script's bug?

**Comment by liding58** [comment]
btw,
https://i.pximg.net/img-original/img/2020/06/30/22/12/58/82660315_p0.png
is not latest path, but
https://i.pximg.net/img-original/img/2020/07/02/11/23/24/82660315_p0.png

seems a update on it

**Comment by journey-ad** [comment]
为了减少对Pixiv服务器的请求，作品详情数据会被永久缓存，你可以在获取作品详情时使用`action=update`参数来刷新缓存
示例： `https://api.imjad.cn/pixiv/v2/?id=82660315&action=update`

这个项目试验的性质居多，因此并未对作品有更新的情况作处理
